### ISSUE TITLE
我想用户在点击一个组件时，自动与另一个组件连一条线

### ISSUE THREAD

**Issue by laomaolaile** [Grnetsky/meta2d_vue#13]
我想用户在点击一个组件时，自动与另一个组件连一条线，请问有没有什么好的实现方法？

**Comment by Grnetsky** [comment]
看meta2d的文档哈，里面有连线的函数

**Comment by laomaolaile** [comment]
没怎么看懂。。我是想用代码实现，大概做了一个demo,但是没有达到我想要的效果。请大佬指导一下，谢谢了

![image](https://github.com/user-attachments/assets/8edcf3a1-8f30-49f4-83b9-8fee29112445)


![image](https://github.com/user-attachments/assets/0745dd23-4440-471c-842c-acc551a5f9ac)

**Comment by Grnetsky** [comment]
![image](https://github.com/user-attachments/assets/2f3e11ab-9538-4ad4-b91a-70c8eaba5d71)
官网文档里有 自己找一下就能找到

**Comment by laomaolaile** [comment]
确实，问题解决了。非常感谢。
